// Generated by CoffeeScript 1.3.3
(function() {

  $(document).bind("mousemove", function(e) {
    return $("#gun").css({
      left: e.pageX - 125,
      top: e.pageY - 125
    });
  });

  $(document).bind("mousedown", function(e) {
    return $("<div class='awkward_cat'></div>").appendTo("body").css({
      left: e.pageX - 125,
      top: e.pageY - 125
    });
  });

  // $("#cats").hover(
  // 	function(e){ console.log("hove") },
  // 	function(e){ $("#gun").hide(); }
  // );

}).call(this);
